name = "gh-stats-api"

compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

build.command = "pnpm build"
main = "dist/index.js"

observability.enabled = true

[observability.logs]
enabled = true
